[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
addopts = "--cov=pythion"
testpaths = ["tests",]

[tool.mypy]
mypy_path = "src"
strict = true
exclude = ['/_layout/']
follow_imports = "silent"